sudo: false
py35-steps:
  env: &1
  - PATH=/c/Users/travis/AppData/Roaming/Python/Python35/Scripts:/c/Python35:/c/Python35/Scripts:/c/Users/travis/AppData/Roaming/Python/Python35/Scripts:$PATH
  - TOXENV=py35
  before_install: &2
  - choco install python --version 3.5.4
  - python -m pip install --upgrade pip
  - pip install --user tox
py36-steps:
  env: &3
  - PATH=/c/Users/travis/AppData/Roaming/Python/Python36/Scripts:/c/Python36:/c/Python36/Scripts:/c/Users/travis/AppData/Roaming/Python/Python36/Scripts:$PATH
  - TOXENV=py36
  before_install: &4
  - choco install python --version 3.6.8
  - python -m pip install --upgrade pip
  - pip install --user tox
py37-steps:
  env: &5
  - PATH=/c/Users/travis/AppData/Roaming/Python/Python37/Scripts:/c/Python37:/c/Python37/Scripts:/c/Users/travis/AppData/Roaming/Python/Python37/Scripts:$PATH
  - TOXENV=py37
  before_install: &6
  - choco install python --version 3.7.8
  - pip install --user tox
matrix:
  include:
  - name: py35-linux
    python: 3.5
    env: TOXENV=py35
    os: linux
    language: python
  - name: py36-linux
    python: 3.6
    env: TOXENV=py36
    os: linux
    language: python
  - name: py37-linux
    python: 3.7
    env: TOXENV=py37
    dist: xenial
    os: linux
    language: python
  - name: docu
    python: 3.6
    env: TOXENV=docu
    os: linux
    language: python
  - name: coverage
    python: 3.6
    env: TOXENV=coverage
    os: linux
    language: python
  - name: py35-windows
    python: 3.5
    env: *1
    os: windows
    language: shell
    before_install: *2
  - name: py36-windows
    env: *3
    os: windows
    language: shell
    before_install: *4
  - name: py37-windows
    env: *5
    os: windows
    language: shell
    before_install: *6
script:
- tox -e "${TOXENV}"
deploy:
  provider: pypi
  user: MKoesters
  distributions: sdist bdist_wheel bdist_egg
  on:
    tags: true
    all_branches: true
    skip_existing: true
    skip_cleanup: true
  password:
    secure: RjGbT2F5A52GFZfUze5nDZ0lrr53iT7b/mbBAUzh1cJzXiQIJTOLSQVA3bmh5ALbiYZ4ug/evBKpqVx7p6h3/xylUzVf2Oz+eETL8vl5vvLdi/aVbOT3eTMVROvOMXd7xgNnLqDzhutcMuw1EFtOHmlQAqqXNR6SwOBRvCyUlhq+HB9X6P7Z9L0sZs9lQUzbipgTEfKEY+gSTZc2w8t5myrxoaAL8tXk2uJD9gJoxrx9nz+XsmnHtgtdsp5I8lvTqSExvM4/HkwkrNk5deKlSxz3p4rkhL+gcHTi0fQMPSPfTipBFkIq5RPRMkjaK3KQBkQMXLvlnTYUFHBwMkwrF/W0RXhZpsfyUNDFh90OC4E2/x2YFrSQRoH1i8rnJxpfMVrJa/JAiCA5Ky4D6acY3c59c4KpQ+XFdBU8bmxriQ/NgEp120hFwzlInEpINmDZkg3mkvf4SFKUgoTpO36Tjwk5DXZc4BTQg/Q00xTET7iYBrcui9bLDiN/oQUm0O4M+os5n1GmprwOSHbcHXY3PLvZc01E5VjgiHnTO1XwD5k0PZ2uCIksspRb4+36AikzG1pG13B54K0RyiQ7syaEGg06I14uxJrIGZ6jABvjgSiD4XdIhtltTIDeNNkB+Gc0w2q702eLlz1afg9ZpDxhgsgyY5ywQYUsG6c+nc4nxpU=
