name: Black Check
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
      branches:
        - dev
        - master

jobs:
  build:
    # Job name is Greeting
    name: black-isort
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: CurDir
        run: pwd;ls
      - name: Python Lint (isort/black)
        uses: wrboyce/python-lint-action@v1.0.0
